$('#modal').html('')
$("<%= escape_javascript(render 'tasks/edit')%>").appendTo('#modal').hide()
$('#myModal').on('hidden', -> $('#modal').html('') )
$('#myModal').modal('show')
$('#task_deadline').datetimepicker({minDate: new Date()})